name: rick_and_morty_riverpod
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  freezed_annotation: ^2.0.3
  go_router: ^3.1.1
  hooks_riverpod: ^2.0.0-dev.9
  json_annotation: ^4.5.0
  lazy_load_scrollview: ^1.3.0
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.0.1+1
  sizing:
    path: ./packages/sizing

dev_dependencies:
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.2.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rick and Morty
      fonts:
        - asset: assets/fonts/rick_and_morty_font.ttf

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"
