name: sizing
description: Simple package to handle scaling / responsive user interfaces (UI) on different screen sizes.
version: 1.1.1
homepage: https://github.com/liontude/sizing

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
